"""create extraction_runs

Revision ID: 7629504d530a
Revises: 
Create Date: 2026-02-20 01:02:35.563504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7629504d530a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_runs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='extraction_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint('char_length(input_text) <= 20000', name='ck_extraction_runs_input_text_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_extraction_runs_user_idempotency')
    )
    op.create_index('ix_extraction_runs_user_created', 'extraction_runs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extraction_runs_user_created', table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.execute("DROP TYPE IF EXISTS extraction_status")
    # ### end Alembic commands ###
